version: '{build}'
pull_requests:
  do_not_increment_build_number: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_API_KEY:
    secure: 0omP7ZyN6aN+7n6uOq+rafpMcXhuqW9FPGHBx3rKRy02UbEoqX2FPeyHrnzfUZhV
build_script:
- ps: .\build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet