version: '{build}'
pull_requests:
  do_not_increment_build_number: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_API_KEY:
    secure: YLa6nMl5j0h1Jtm03BwnrH787AxhJMoHH3Txpr5XllMV7RzWMeYKxCW3zVMTAhQR
build_script:
- ps: .\build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet